#!/bin/bash /opt/app/osaaf/local/org.onap.dmaap-dr.check.sh
# Certificate Manager Check Script
# Check on Certificate, and renew if needed.
# Generated by Certificate Manager 2018-08-17T16:18:06.508Z
DIR=/opt/app/osaaf/local
APP=org.onap.dmaap-dr
EMAIL=jonathan.gathman@us.att.com
CP="/opt/app/aaf_config/bin/aaf-cadi-aaf-*-SNAPSHOT-full.jar"
> $DIR/$APP.msg

function mailit {
  if [ -e /bin/mail ]; then
     MAILER=/bin/mail
  elif [ -e /usr/bin/mail ]; then 
     MAILER=/usr/bin/mail
  else 
     MAILER=""
  fi
 if [ "$MAILER" = "" ]; then
    printf "$*"
 else 
    printf "$*" | $MAILER -s "AAF Certman Notification for `uname -n`" $EMAIL
 fi
}

/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java -cp $CP org.onap.aaf.cadi.configure.Agent cadi_prop_files=$DIR/$APP.props check 2>  $DIR/$APP.STDERR > $DIR/$APP.STDOUT
case "$?" in
  0)
    # Note: Validation will be mailed only the first day after any modification
    if [ "`find $DIR -mtime 0 -name $APP.check.sh`" != "" ] ; then
       mailit `echo "Certficate Validated:\n\n" | cat - $DIR/$APP.msg`
    else
       cat $DIR/$APP.msg
    fi
    ;;
  1) mailit "Error with Certificate Check:\\n\\nCheck logs $DIR/$APP.STDOUT and $DIR/$APP.STDERR on `uname -n`"
    ;;
  2) mailit `echo "Certificate Check Error\\n\\n" | cat - $DIR/$APP.msg`
    ;;
  10) mailit `echo "Certificate Replaced\\n\\n" | cat - $DIR/$APP.msg`
      if [ -e $DIR/$APP.restart.sh ]; then
        # Note: it is THIS SCRIPT'S RESPONSIBILITY to notify upon success or failure as necessary!!
        /bin/sh $DIR/$APP.restart.sh
      fi
    ;;
  *) mailit `echo "Unknown Error code for CM Agent\\n\\n" | cat - $DIR/$APP.msg`
    ;;
 esac

 # Note: make sure to cover this sripts' exit Code
