#!/bin/bash /opt/app/osaaf/local/org.onap.dmaap-dr.crontab.sh
# Certificate Manager Crontab Loading Script
# Add/Update a Crontab entry, that adds a check on Certificate Manager generated Certificate nightly.
# Generated by Certificate Manager 2018-08-17T16:28:26.224Z
TFILE="/tmp/cmcron$$.temp"
DIR="/opt/app/osaaf/local"
CF="org.onap.dmaap-dr Certificate Check Script"
SCRIPT="/opt/app/osaaf/local/org.onap.dmaap-dr.check.sh"
crontab -l | sed -n "/#### BEGIN $CF/,/END $CF ####/!p" > $TFILE
# Note: Randomize Minutes (0-60) and hours (1-4)
echo "#### BEGIN $CF ####" >> $TFILE
echo "$(( $RANDOM % 60)) $(( $(( $RANDOM % 3 )) + 1 )) * * * /bin/bash $SCRIPT >> $DIR/cronlog 2>&1 " >> $TFILE
echo "#### END $CF ####" >> $TFILE
crontab $TFILE
rm $TFILE
