#!/bin/bash
# ============LICENSE_START=======================================================
# org.onap.dmaap
# ================================================================================
# Copyright © 2018 AT&T Intellectual Property. All rights reserved.
# ================================================================================
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ============LICENSE_END=========================================================
#
# ECOMP is a trademark and service mark of AT&T Intellectual Property.


JAVA_HOME=/opt/java/jdk/jdk180
JAVA_OPTS="-Xms1G -Xmx1G"
TZ=GMT0
PATH=$JAVA_HOME/bin:/bin:/usr/bin
CLASSPATH=`echo /opt/app/datartr/etc /opt/app/datartr/lib/*.jar | tr ' ' ':'`
export CLASSPATH JAVA_HOME JAVA_OPTS TZ PATH

$JAVA_HOME/bin/java \
    -Dlog4j.configuration=file:///opt/app/datartr/etc/log4j.drroute.properties \
    org.onap.dmaap.datarouter.provisioning.utils.DRRouteCLI $*
