#!/bin/bash
# ============LICENSE_START=======================================================
# org.onap.dmaap
# ================================================================================
# Copyright © 2018 AT&T Intellectual Property. All rights reserved.
# ================================================================================
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ============LICENSE_END=========================================================
#
# ECOMP is a trademark and service mark of AT&T Intellectual Property.


umask 0022

JAVA_HOME=/opt/java/jdk/jdk180
JAVA_OPTS="-Xms1G -Xmx4G"
JAVA_CLASS=org.onap.dmaap.datarouter.reports.Report
TZ=GMT0
PATH=$JAVA_HOME/bin:/bin:/usr/bin
CLASSPATH=`echo /opt/app/datartr/etc /opt/app/datartr/lib/*.jar | tr ' ' ':'`
LOGDIR=/opt/app/datartr/logs
YESTERDAY=`/bin/date --date=yesterday '+%Y%m%d'`

export CLASSPATH JAVA_HOME JAVA_OPTS TZ PATH

ID=`id -n -u`
GRP=`id -n -g`
if [ "$ID" != "datartr" ]
then
	echo runreports must be started as user datartr not $ID
	exit 1
fi
if [ "$GRP" != "datartr" ]
then
	echo runreports must be started as group datartr not $GRP
	exit 1
fi
if [ "`pgrep -u mysql mysqld`" = "" ]
then
	echo MySQL is not running.  It must be started before runreports
	exit 1
fi

# Volume report
java $JAVA_OPTS $JAVA_CLASS -t volume -o $LOGDIR/volume.csv.$YESTERDAY yesterday </dev/null >/dev/null

# Subscriber report
java $JAVA_OPTS $JAVA_CLASS -t subscriber -o $LOGDIR/subscriber.csv.$YESTERDAY yesterday </dev/null >/dev/null

exit 0
